# Generated by Django 3.0.3 on 2020-04-27 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='renter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.Address'),
        ),
        migrations.AddField(
            model_name='property',
            name='posted_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AddField(
            model_name='image',
            name='Property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rentals.Property'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='reservation',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='rentals.Reservation'),
        ),
    ]
