# Generated by Django 3.0.3 on 2020-04-27 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid_initial', models.CharField(max_length=1)),
                ('dl_number', models.CharField(max_length=12)),
                ('is_landlord', models.BooleanField(default=False)),
                ('address', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='rentals.Address')),
                ('user', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
